# Generated by Django 3.2.13 on 2022-05-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('emails', models.EmailField(max_length=254)),
                ('read', models.BooleanField(default=False, verbose_name='read')),
                ('choice', models.IntegerField(choices=[(0, 'PENDING'), (1, 'ACCEPTED'), (2, 'REFUSED')], default=0, verbose_name='choice')),
                ('code', models.IntegerField(default=0, null=True, verbose_name='code')),
            ],
        ),
    ]
