# Generated by Django 3.2.13 on 2022-05-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='emails',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
