# Generated by Django 3.2.13 on 2022-06-03 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_app', '0002_alter_guest_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='group_seat',
            field=models.IntegerField(choices=[(0, ''), (1, 'VIP LEFT'), (2, 'VIP RIGHT'), (3, 'Table 1'), (4, 'Table 2'), (5, 'Table 3'), (6, 'Table 4'), (7, 'Table 5'), (8, 'Table 6'), (9, 'Table 7')], default=0, verbose_name='group seat'),
        ),
    ]
