# Generated by Django 3.2.13 on 2022-06-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_app', '0004_alter_guest_group_seat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='group_seat',
            field=models.IntegerField(choices=[(0, 'LOVE COUCH'), (1, 'VIP LEFT'), (2, 'VIP RIGHT'), (3, 'Table 1'), (4, 'Table 2'), (5, 'Table 3'), (6, 'Table 4'), (7, 'Table 5'), (8, 'Table 6'), (9, 'Table 7'), (10, 'Table 8'), (11, 'NONE')], default=0, verbose_name='group seat'),
        ),
    ]
